N = int(input())

print("1 x {} = {}".format(N, 1*N))
print("2 x {} = {}".format(N, 2*N))
print("3 x {} = {}".format(N, 3*N))
print("4 x {} = {}".format(N, 4*N))
print("5 x {} = {}".format(N, 5*N))
print("6 x {} = {}".format(N, 6*N))
print("7 x {} = {}".format(N, 7*N))
print("8 x {} = {}".format(N, 8*N))
print("9 x {} = {}".format(N, 9*N))
print("10 x {} = {}".format(N, 10*N))